image: ubuntu/latest

sources:
- https://git.sr.ht/~tsileo/entries
tasks:
- lints: |
    apt-get update && apt-get install -y python3-pip python3-dev && cd /usr/local/bin && ln -s /usr/bin/python3 python && pip3 install --upgrade pip
    pip install black flake8 mypy
    black --check .
    flake8 cli.py
    mypy --ignore-missing-imports cli.py
